name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set image name
        id: vars
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$(basename ${{ github.repository }})" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME:latest

      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest
