name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile with Maven
        run: mvn clean compile

      - name: Build the Docker image with repo name as tag
        run: |
          IMAGE_NAME=${GITHUB_REPOSITORY##*/}
          docker build . --file Dockerfile --tag $IMAGE_NAME:latest
